# To run: conda env create -f environment.yml
name: ultra_nerf
channels:
    # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - jax
    - tensorflow-probability
    - cudatoolkit=11.0
    # - cudnn
    - scikit-learn
    - cudnn=8.2
    - numpy
    - matplotlib
    - imageio==2.19.3
    - imageio-ffmpeg
    - configargparse
    - tensorflow==2.8
    - tensorflow-gpu==2.8
